name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint and Format Check
        uses: ./.github/actions/lint-and-format

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Unit Tests
        uses: ./.github/actions/unit-test

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    permissions:
      contents: read
      deployments: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.url }}

    env:
      CF_PAGES: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build for Cloudflare Pages
        env:
          PUBLIC_ENV_NAME: production
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run build

      - name: Deploy to Cloudflare Pages
        id: deployment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name='${{ secrets.CLOUDFLARE_PROJECT_NAME }}'
