name: Pull Request

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel previous runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint and Format Check
        uses: ./.github/actions/lint-and-format

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Unit Tests
        uses: ./.github/actions/unit-test
        with:
          with-coverage: 'true'

      - name: Upload unit test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 30

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: lint
    environment: supabase-integration
    if: github.event.pull_request.draft == false

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_ID: ${{ secrets.USER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run E2E Tests
        uses: ./.github/actions/e2e-test

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

  status-comment:
    name: Status Comment
    runs-on: ubuntu-latest
    needs: [lint, unit-test, e2e-test]
    if: always() && github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create status comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🚀 Pull Request Status Report

            **Commit:** ${{ github.sha }}
            **Branch:** ${{ github.head_ref }}

            ### Test Results:
            - **Linting:** ${{ needs.lint.result == 'success' && '✅ Passed' || '❌ Failed' }}
            - **Unit Tests:** ${{ needs.unit-test.result == 'success' && '✅ Passed' || '❌ Failed' }}
            - **E2E Tests:** ${{ needs.e2e-test.result == 'success' && '✅ Passed' || '❌ Failed' }}

            ### Overall Status:
            ${{ needs.lint.result == 'success' && needs.unit-test.result == 'success' && needs.e2e-test.result == 'success' && '🎉 All checks passed! Ready for review.' || '⚠️ Some checks failed. Please review the errors above.' }}

            ---
            *This comment is automatically updated on each push to the PR.*
